name: Release OTA update
on: workflow_dispatch
# Note - on-demand builds will use the version of the script that is in the master branch, even if you run a build on
# a non-master branch

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm i
      - name: Get env
        uses: falti/dotenv-action@v0.2.5
        with:
          path: .env.template
          log-variables: true
      - name: GitHub Action for Codepush
        uses: NishanthShankar/codepush-action@0.1
        with:
          args: release-react -a mr.kirill/Test-App -d Staging -t $VERSION
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APP_CENTER_KEY }}
          VERSION: ${{ steps.dotenv.outputs.version }}   
